# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poke',
            old_name='poked',
            new_name='poked_by',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='created_at',
        ),
    ]
