# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke_app', '0002_auto_20171028_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='total',
        ),
    ]
